[package]
name = "nbstripout_rust"
version = "0.1.0"
authors = ["Daisuke Shimamoto <diskshima@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.1"
json = "0.12.4"
